wipe_nav:
  animate: swipe

title: Home
views:
  - !include dashboards/home/dashboard.yaml
  - !include dashboards/home/brandweer.yaml
  - !include dashboards/home/power.yaml
  - !include dashboards/home/calendar.yaml
  - !include dashboards/home/cameras.yaml
