wipe_nav:
  animate: swipe

title: Home
views:
  - !include dashboards/home/home.yaml
  - !include dashboards/home/brandweer.yaml
  - !include dashboards/home/aquarium.yaml
  - !include dashboards/home/power.yaml
  - !include dashboards/home/calendar.yaml
  - !include dashboards/home/cameras.yaml
