wipe_nav:
  animate: swipe

title: Home
views:
  - !include dashboards/home/dashboard.yaml
  - !include dashboards/home/calendar.yaml
  - !include dashboards/home/cameras.yaml
  - !include dashboards/home/nest_hub.yaml
  - !include dashboards/home/yams.yaml
