wipe_nav:
  animate: swipe

button_card_templates: !include dashboards/home/overzicht_templates.yaml

title: Home
views:
  - !include dashboards/home/overzicht.yaml
  - !include dashboards/home/dashboard.yaml
  - !include dashboards/home/calendar.yaml
  - !include dashboards/home/cameras.yaml
  - !include dashboards/home/nest_hub.yaml
  - !include dashboards/home/yams.yaml
