automations_package:
  template:
    - sensor:
        - name: "Lopende Automatiseringen"
          state: "{{ states.automation
  | selectattr('attributes.current', 'defined')
  | selectattr('attributes.current', '>', 0)
  | map(attribute='name') | join('\n') }}"
