automations_package:
  template:
    - sensor:
        - name: "Lopende Automatiseringen"
          unique_id: lopende_automatiseringen
          state: "{{ states.automation
  | selectattr('attributes.current', 'defined')
  | selectattr('attributes.current', '>', 0)
  | map(attribute='name') | join('\n') }}"

    - binary_sensor:
        - name: Work - Maybe travel to work time
          unique_id: maybe_travel_to_work
          state: >-
            {{ (now().hour >= 6 and now().hour <= 13) }}
